### ISSUE TITLE
The plugin does not have a valid header.

### ISSUE THREAD

**Issue by cardinal79** [mattbanks/woocommerce-local-pickup-time#13]
When I try to activate the plugin I get the message that the plugin does not have a valid header.

Also, ETA on update for future date selection for pickup date and time.

**Comment by mattbanks** [comment]
Installed on 2 existing sites and 2 new sites (1 local, 1 hosted) and didn't see any errors with the plugin. There could be a caching issue (see here: https://scotty-t.com/2011/03/28/fix-for-the-plugin-does-not-have-a-valid-header/).

Not sure what you're referring to about future date selection?

**Comment by timnolte** [comment]
> Also, ETA on update for future date selection for pickup date and time.

@cardinal79 have you checked out the most recent version? I added expanded date selection. Perhaps you can open up a new issue for that specifically indicating in detail what you are looking for?
