### ISSUE TITLE
Refactor Plugin to Follow WordPress PHP Coding Standards Using PHP_CodeSniffer

### ISSUE THREAD

**Issue by timnolte** [mattbanks/woocommerce-local-pickup-time#16]
In order to allow for more open contributions by developers the plugin should follow the [WordPress PHP Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/). The best way to handle this is to use build tools and the [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) rules built for [WP Code Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards).

**Comment by timnolte** [comment]
@mattbanks if this is acceptable to you I'm going to work this through. I've sort of already started on this. If all the code passes the general WP PHP coding standards it will really make code reviews much easier, I'd actually like to add a TravisCI config, to help with automating PR checks, as well as run unit test(which I'm also already working on starting). I'm just looking to help us all out.

**Comment by mattbanks** [comment]
Hey @timnolte that would be amazing! You've done an amazing job contributing here! Would you be interested in becoming a co-maintainer/author for the plugin? I can give you access in the repo and Committer access on wordpress.org to push updated to the plugin.

**Comment by mattbanks** [comment]
@timnolte Awesome! I'll add you as a collaborator to the repo today and I can add you to the wp.org collaborators list for plugin deploys over the weekend! :)

**Comment by mattbanks** [comment]
@timnolte You have commit access in SVN now to push new versions to wp.org :)

**Comment by timnolte** [comment]
@mattbanks I have Travis CI tasks building my own fork/branches, hopefully we can get this working fully for the main branch as well. FYI, there is also now a Grunt task that will take care of the WordPress SVN publish instead of using the shell script. When you run a grunt build everything will get staged and then a grunt wp_deploy will perform the needed SVN checkout and copy the staging files over for deployment, it also prompts for SVN credentials so whoever is doing the push can use their own credentials. Thanks!

**Comment by mattbanks** [comment]
sweet dude! let me know whatever you need me to do to get Travis setup.

**Comment by timnolte** [comment]
> sweet dude! let me know whatever you need me to do to get Travis setup.

@mattbanks if you can go to [Travis CI](https://travis-ci.org/mattbanks/woocommerce-local-pickup-time) and login and authorize Travis with access to your main repo I think we'll be in business. I've started a Project for a 1.4 release which will be a feature release with the beginning of unit tests. My intent will be at the very least to write new unit tests for any new features. If there are patches, for older code, then unit tests will be written to confirm the bug and verify the fix. There is still some cleanup that needs to occur, and some documentation so that it's clear to all the workflow needed for a new release that includes all the build steps from PR to WordPress.org release. My hope is that if it's well documented then neither you, or I need to guess what the other is doing and we don't run into release problems. Thanks again for bringing me on board!

**Comment by mattbanks** [comment]
Travis is now activated for the repo! https://travis-ci.org/mattbanks/woocommerce-local-pickup-time

**Comment by timnolte** [comment]
@mattbanks sweet I was able to kick off the first build. I'll have to confirm how the notifications work, hopefully you don't start getting overwhelmed with build notices. 😉

**Comment by mattbanks** [comment]
Haha that's what Gmail's filters are for. lol :)
