### ISSUE TITLE
error language e-mail 

### ISSUE THREAD

**Issue by youpyoup** [mattbanks/woocommerce-local-pickup-time#17]
Hi,

I have a problem on e-mail, the pickup date is not translate (in FR), but ok in front office.
Bug error visible in woocommerce log : 2018-11-29T11:39:05+00:00 CRITICAL Call to undefined method Local_Pickup_Time::pickup_time_select_translatable()
Any idea please ?

With thanks

**Comment by timnolte** [comment]
@youpyoup I have a bug fix that should address this that is almost ready. I was getting caught up in another effort so I'll put a hold on that and get this resolved soon.

**Comment by youpyoup** [comment]
@timnolte ok thanks, let me know when you have resolved this.

**Comment by youpyoup** [comment]
Hi @timnolte, some news concerning the bug fix ? :)
With thanks !

**Comment by timnolte** [comment]
@youpyoup I should have a new release ready by the end of the week.

**Comment by youpyoup** [comment]
Hi @timnolte, the new release is available ? thanks again.

**Comment by timnolte** [comment]
@youpyoup sorry, with the holidays and work the release had been delayed. I'm looking to get it finally pushed out next week.

**Comment by youpyoup** [comment]
No problem thanks @timnolte :)

**Comment by timnolte** [comment]
@youpyoup the translation issues should be resolved now.

**Comment by youpyoup** [comment]
Hi timnolte, i have an rror at the activation : 

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /var/www/clients/client7/web17/web/wp-content/plugins/woocommerce-local-pickup-time-select/public/class-local-pickup-time.php on line 585

**Comment by timnolte** [comment]
@youpyoup what version of PHP are you running?

**Comment by youpyoup** [comment]
For information, i have test to desactivate all my plugins and reactivate only woocommerce + local pickup time

**Comment by youpyoup** [comment]
Whats your opinion for the error @timnolte  ?

**Comment by timnolte** [comment]
@youpyoup that error should not exist now on the 1.3.4 release. The 1.3.3 release missed applying the patch for PHP 5.6. Ate you certain you are running on PHP 5.6 and running version 1.3.4?
