### ISSUE TITLE
Longer time?

### ISSUE THREAD

**Issue by ProGear360** [mattbanks/woocommerce-local-pickup-time#18]
Hi there!
I need to add about a 3 day (4320) delay, how would I go about adding that as an option?

Regards,
Jay

**Comment by timnolte** [comment]
@ProGear360 I've got a big commit coming with a bug fix and some enhancements. How soon do you need this change made. I'd probably look at changing this to a numeric entry with a type dropdown(minutes, hours, days) and then let an admin just set pretty much any sort of delay they'd like.

**Comment by ProGear360** [comment]
@timnolte Big commits are the best!
I'm opening my little shop on Monday :)
I'm not quite sure how to do that unfortunately.

**Comment by timnolte** [comment]
@ProGear360 I'll see if I can't get something working for you by  the end of the weekend.

**Comment by ProGear360** [comment]
@timnolte That would honestly be amazing!

**Comment by timnolte** [comment]
@ProGear360 so I have a change that you can probably use, but you'll need to pull the plugin from [my GitHub](https://github.com/timnolte/woocommerce-local-pickup-time) fork, specifically the `feature/pickup-date-order-sort` branch. I like to use the [GitHub Updater Plugin](https://github.com/afragen/github-updater) for this sort of thing.

**Comment by ProGear360** [comment]
I thought I replied, apparently it didn't come through!
Thanks Tim!
Just a heads up, there's a bug when you pick 3 days and 5 days, it comes up with:
Warning: DateTime::setTime() expects parameter 1 to be integer, string given in /home/user/public_html/wp-content/plugins/woocommerce-local-pickup-time-feature-pickup-date-order-sort/public/class-local-pickup-time.php on line 449

**Comment by timnolte** [comment]
@ProGear360 sorry about that, I was running short on time and was trying to get something quick and dirty to you. Obviously a little more dirty than I had hoped. I'll run that down and commit a fix for that tonight hopefully.

**Comment by timnolte** [comment]
@ProGear360 it seems like 1, or more, of your open/close times is either a different time format than what the plugin is expecting, or as I've tested it they are set to an empty open/close time. I just updated the plugin code to account for the case where there could be empty open/close times. Give it a try now, otherwise if you could provide me the format you are using I can determine a fix. Thanks!

**Comment by timnolte** [comment]
@ProGear360 the latest 1.3.2 release should have what you need now.
