### ISSUE TITLE
Syntax error introduced in last patch

### ISSUE THREAD

**Issue by craisis** [mattbanks/woocommerce-local-pickup-time#26]
https://github.com/mattbanks/woocommerce-local-pickup-time/blob/08e3cd1cd4902ecc3f8327bba56134fb8a18a738/public/class-local-pickup-time.php#L585

[04-Feb-2019 16:06:52 UTC] PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in <REDACTED>/wp-content/plugins/woocommerce-local-pickup-time-select/public/class-local-pickup-time.php on line 585

Due to wrapping DateTime::createFromFormat in ()'s before >getTimestamp().

**Comment by craisis** [comment]
#27

**Comment by timnolte** [comment]
@craisis can you confirm which version of PHP this error occurs for? I wasn't able to reproduce on any of my dev instances but they are all running a 7.x version of PHP. I'm going to begin creation of unit tests starting in the 1.4 release, along with CI builds with a matrix of PHP/WP/WC versions, so as to hopefully prevent these sorts of issues going forward.

**Comment by craisis** [comment]
@timnolte  Tested using PHP 5.6. 

`[root@wc-php-test yum.repos.d]# php -v
PHP 5.6.40 (cli) (built: Jan  9 2019 12:34:16) 
`

Simple test with only this line results in:
`PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /root/test.php on line 2`

Removing outer ('s:
`PHP Fatal error:  Using $this when not in object context in /root/test.php on line 2`

**Comment by timnolte** [comment]
Not sure why things ended up being so difficult but this fix is deployed and released. Thanks!

**Comment by timnolte** [comment]
Looks like I somehow got tripped up as it seemed there was originally a change to add the () around the call, but now I see that this removes them. I'll need to reapply this patch once again.
