### ISSUE TITLE
Pickup times are not handled properly

### ISSUE THREAD

**Issue by tomaski** [mattbanks/woocommerce-local-pickup-time#44]
Using plugin version 1.3.8
WP version 5.1.1

pickup timeframe set from 12:00 to 20:00
with 15 min intervals, 30 min delay and 1 day ahead

on order page, last possible pickup time is set to 19:45 (should be 20:00)
also, as I'm writing this, it's 17:32 and plugin allows for selecting 17:35 pickup (expected 18:15 as earliest possible)

**Comment by timnolte** [comment]
@tomaski to address the point that the last pickup time is 19:45 instead of 20:00 it went with the fact that it is expected that 20:00 is your close time, so you wouldn't allow a pickup right at close. So this is as designed.

The point of it being 17:32 and it is allowing you to select 17:35 looks completely wrong, as I would expect at the worst case 17:45, which would also be wrong. You are correct that the next pickup time should reflect 18:15 given there is a 30 minute delay.

**Comment by tomaski** [comment]
@timnolte
Thank you for your swift response. 👍

My bad, then. I was under the assumption that (since it is a pickup-related
plugin) the times, I set up are for the pickups only, as a restaurant can
(and in my case does) have pickup time frame that differs from opening
times.
Maybe then a select box in the setting whether one does wish to have a
pickup on closing time?
(in case there are more tomaskies 😉)

śr., 27 mar 2019, 18:06 użytkownik Tim Nolte <notifications@github.com>
napisał:

**Comment by timnolte** [comment]
@tomaski no, you aren't the only one to misunderstand this and it really is a point of confusion and should be addressed. I need to talk with @mattbanks on this as there is also a request to the into the WooCommerce store closed notice which makes this a sticky point.

**Comment by tomaski** [comment]
@timnolte I see that this issue is being worked on. nice :)
However, I just came across another unexpected behavior:
Let's say I started placing an order at 14:00. Fisrst possible pickup was 14:30 and that is what I chose. If I then get distracted / interrupted and do not finish the order immediately, but at 14:35. My order will be accepted!
Can you check it please?

**Comment by mattbanks** [comment]
@timnolte What would need to change with the store close notice? Sorry, I've been away from the plugin for a bit and haven't looked too much at what's going on (been swamped with work and family stuff).

**Comment by timnolte** [comment]
> @timnolte I see that this issue is being worked on. nice :)
> However, I just came across another unexpected behavior:
> Let's say I started placing an order at 14:00. Fisrst possible pickup was 14:30 and that is what I chose. If I then get distracted / interrupted and do not finish the order immediately, but at 14:35. My order will be accepted!
> Can you check it please?

@tomaski OK, that's a good point. I would sort of classify this as more of an enhancement versus a bug. We'll need to add some validation on checkout. If you wouldn't mind opening up a new issue for that functionality I'd appreciate it.

**Comment by timnolte** [comment]
> @timnolte What would need to change with the store close notice? Sorry, I've been away from the plugin for a bit and haven't looked too much at what's going on (been swamped with work and family stuff).

@mattbanks the big question is the plugin "store hours" and making sure that it appropriate to make these open/close times as strictly pickup begin/end times. So then tying into the store notice would be to provide a banner indicating that no more pickups are available for the current day.

**Comment by mattbanks** [comment]
> @mattbanks the big question is the plugin "store hours" and making sure that it appropriate to make these open/close times as strictly pickup begin/end times. So then tying into the store notice would be to provide a banner indicating that no more pickups are available for the current day.

Ah gotcha! I think that would need to be an optional think (checkbox, maybe other metadata with it if needed?). Not every store will have the same open/close hours as pickup hours (the store this plugin was originally designed for would be in that boat), so we would need to account for both options.
