### ISSUE TITLE
Add today as pickup option

### ISSUE THREAD

**Issue by mkelley15** [mattbanks/woocommerce-local-pickup-time#56]
Is there a way to add today as a pickup option? You have "Pickup Time Open Days Ahead" set as "inclusive to the current day if timeslots are available" however, I can't use today as a pickup time on the cart page.

**Comment by timnolte** [comment]
Can you please provide the following details. This should work but is dependent on your settings.

Website URL

PHP Version

WordPress Version

WooCommerce Version

Plugin Version

WordPress Timezone Setting

WordPress Date Format Setting

WordPress Time Format Setting

All Plugin Start/End Pickup Time Settings

Plugin Pickup Time Interval Setting

Plugin Pickup Time Delay Setting

Plugin Pickup Time Open Days Ahead Setting

**Comment by mkelley15** [comment]
Thanks for getting to me so quickly.  I didn't even think to double check my WP time zone.  I had chosen city and NOT UTC, which was causing an error.  I changed it to the correct UTC and all is working correctly now.  Thank you so much!

**Comment by timnolte** [comment]
@mkelley15 great to hear you figured out the issue. The timezone is a pretty big key and has caused some pain points for us in the past.
