### ISSUE TITLE
Strange pickup time..

### ISSUE THREAD

**Issue by rjgough** [mattbanks/woocommerce-local-pickup-time#6]
My hours are set to shut off the pickup time at 20:00 thursday.. and open 11:00 - 21:00 friday. 

When i place an order, it then tells me the next available time is tomorrow at 20:30 - it seems the only available time is tomorrow past the current time (the current time is 20:00 thursday). 

something a little confusing with this time selection

**Comment by vyskoczilova** [comment]
Hi @rjgough I hope that I have fixed it in my pull request, if you still need it, you can have a look here: https://github.com/mattbanks/woocommerce-local-pickup-time/pull/8
