### ISSUE TITLE
Plugin v1.3.11 Crashes Order Page on TwentySeventeen Theme

### ISSUE THREAD

**Issue by timnolte** [mattbanks/woocommerce-local-pickup-time#70]
https://twitter.com/jottes/status/1239586116543660032

The latest version does not work but crash the order page. Theme ist twentyseventeen.

- Website URL: 
- PHP Version: 
- WordPress Version: 
- WooCommerce Version: 
- Plugin Version: 1.3.11
- WordPress Timezone Setting: 
- WordPress Date Format Setting: 
- WordPress Time Format Setting: 
- All Plugin Start/End Pickup Time Settings: 
- Plugin Pickup Time Interval Setting: 
- Plugin Pickup Time Delay Setting: 
- Plugin Pickup Time Open Days Ahead Setting:

**Comment by jottesjs** [comment]
Website URL: www.stemke.gd
    PHP Version: 7.3
    WordPress Version: 5.2.4.
    WooCommerce Version: 4.0.0 (or earlier)
    Plugin Version: 1.3.11
    WordPress Timezone Setting: Berlin
    WordPress Date Format Setting: l, j. F Y (or "other")
    WordPress Time Format Setting: G:i
    All Plugin Start/End Pickup Time Settings: 
Start: Mo-Sa: 6:30
End: Mo-Fr: 17:30; Sa: 12:30
Sunday: no setting
    Plugin Pickup Time Interval Setting: 30 minutes
    Plugin Pickup Time Delay Setting: 36 h
    Plugin Pickup Time Open Days Ahead Setting: 66

Symptom: on checout page it shows:
"Pickup Time

The site is experiencing technical difficulties.
"

Checkout-Button is missing

**Comment by jottesjs** [comment]
Workaround to fix the issue: 
Rollback to Plugin Version: 1.3.10

**Comment by jottesjs** [comment]
Also using Woocommerce Germanized plugin. That plugin does things at the check out. Maybe there is a conflict with the latest Pickup?

**Comment by timnolte** [comment]
@jottesjs yes it is very possible that plugin could be causing a conflict. What does that plugin do?

**Comment by jottesjs** [comment]
it does ... pretty much. It installs quite some things to comply with German laws.

you can change the name of the checkout button
it lists product properties in basket and checkout
adds a link to edit basket
shows the basket and thumbnails at checkout
...
https://de.wordpress.org/plugins/woocommerce-germanized/

**Comment by jottesjs** [comment]
The issue seems to be gone, either with Version 1.3.12 or an update of any other conflicting plugin.
