### ISSUE TITLE
Add day of week to pickup time drop down.

### ISSUE THREAD

**Issue by JayneNew** [mattbanks/woocommerce-local-pickup-time#83]
Some customers are selecting the wrong date.  Adding the day of the week to the drop down display may help correct this problem. 

eg. Friday MAY 1, 2020 @ 6"00PM 

Thank you for your consideration.

**Comment by timnolte** [comment]
@JayneNew you can make this happen by changing the WordPress Date format to include the Day, that is how the date & time presented are managed. It may be that we need to provide a plugin specific date format field if changing the WordPress date format is not acceptable.

**Comment by JayneNew** [comment]
Perfect, done. Thanks!
